[package]
name = "cli"
version = "0.1.0"
authors = ["emeryc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mancala = {path = "../mancala"}
rustyline = "6.0.0"